runtime! archlinux.vim

" Plugins
" vim-plug 
call plug#begin('~/.vim/plugged')
    " FZF: fuzzy matching files. Usage: :Files, :FZF, ..
    Plug 'junegunn/fzf.vim'
    " Airline: vim status bar
    Plug 'bling/vim-airline'
    " Airline themes
    Plug 'vim-airline/vim-airline-themes'
    " Gitgutter: show line markers for changed lines
    Plug 'airblade/vim-gitgutter'
    " Polyglot: syntax highlighting for various languages, automatically loaded on demand
    Plug 'sheerun/vim-polyglot'
    " Bufferline: show open buffers - automatically integrated in airline
    Plug 'bling/vim-bufferline'
    " rust.vim: provides Rust file detection, syntax highlighting, formatting, Syntastic integration, and more.
    Plug 'rust-lang/rust.vim'
call plug#end()

" Plugin configuration
" airline theme
let g:airline_theme='deus'

" Keymappings
" map FZF to CTRL+p
nmap <C-p> :Files<CR>
" map :w to CTRL+s
nmap <C-s> :w<CR>
" map :qa! to CTRL+q
nmap <C-q> :qa!<CR>
" map :w!! to 'save file with sudo'
cmap w!! w !sudo tee > /dev/null %

nmap <C-n> :!
nmap <C-c> :! cargo check<CR>
nmap <C-f> :RustFmt<CR>

" Misc settings
" be iMproved, required
set nocompatible              
filetype off
set updatetime=250         
set noswapfile
set undolevels=1000
set backspace=indent,eol,start
set wildmenu
set hidden

" Visuals
set number
set ruler
set linebreak
set showbreak=+++
set showmatch
set visualbell
syntax on
colorscheme slate

" Case sensivity
set hlsearch
set smartcase
set ignorecase
set incsearch
 
" Indentation
set autoindent
set expandtab
" show existing tab with 4 spaces width
set tabstop=4
" when indenting with '>', use 4 spaces width
set shiftwidth=4
" On pressing tab, insert 4 spaces
set expandtab

