runtime! archlinux.vim

" Plugins
" vim-plug 
call plug#begin('~/.vim/plugged')
    " FZF: fuzzy matching files. Usage: :Files, :FZF, ..
    Plug 'junegunn/fzf.vim'
    " Airline: vim status bar
    Plug 'bling/vim-airline'
    " Airline themes
    Plug 'vim-airline/vim-airline-themes'
    " Gitgutter: show line markers for changed lines
    Plug 'airblade/vim-gitgutter'
    " Fugitive: popular git commands. Usage: :Gblame, :Gstatus, ..
    Plug 'tpope/vim-fugitive'
    " Polyglot: syntax highlighting for various languages, automatically loaded on demand
    Plug 'sheerun/vim-polyglot'
    " Commentary: automatically comment out blocks of code. Usage: gcc, gc3j, v<select>gc
    Plug 'tpope/vim-commentary'
    " Closetag: automatically insert closing tags
    Plug 'docunext/closetag.vim'
    " Endwise: automaticall insert 'end' in ruby
    Plug 'tpope/vim-endwise'
    " Bufferline: show open buffers - automatically integrated in airline
    Plug 'bling/vim-bufferline'
    " Eunuch: Commonly used UNIX shell commands as vim commands. Usage: :Delete, :Rename, :Chmod, ..
    Plug 'tpope/vim-eunuch'
    " Emmet: auto expand abbrevations in html etc
    Plug 'mattn/emmet-vim'
call plug#end()

" Plugin configuration
" airline theme
let g:airline_theme='deus'

" Keymappings
" map FZF to CTRL+p
nmap <C-p> :Files<CR>
" map :Buffers (list all buffers - with fuzzy matching) to ;
nmap ; :Buffers<CR>
" map :w to CTRL+s
nmap <C-s> :w<CR>
" map :wq to CTRL+q
nmap <C-q> :q!<CR>
" map :w!! to 'save file with sudo'
cmap w!! w !sudo tee > /dev/null %

" Misc settings
" be iMproved, required
set nocompatible              
filetype off
set updatetime=250         
set noswapfile
set undolevels=1000
set backspace=indent,eol,start
set wildmenu
set hidden

" Visuals
set number
set ruler
set linebreak
set showbreak=+++
set textwidth=100
set showmatch
set visualbell
syntax on
colorscheme delek

" Case sensivity
set hlsearch
set smartcase
set ignorecase
set incsearch
 
" Indentation
set autoindent
set expandtab
set shiftwidth=4
set smartindent
set smarttab
set softtabstop=4
 
